{{- if .Values.agents.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "h2ogpt.fullname" . }}-agents
  namespace: {{ include "h2ogpt.namespace" . | quote }}
  labels:
    app: {{ include "h2ogpt.fullname" . }}-agents
spec:
  replicas: {{ .Values.agents.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "h2ogpt.fullname" . }}-agents
  {{- if .Values.agents.updateStrategy }}
  strategy: {{- toYaml .Values.agents.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.agents.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "h2ogpt.fullname" . }}-agents
        {{- with .Values.agents.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.agents.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agents.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.agents.podSecurityContext | nindent 8 }}
      affinity:
        {{- if .Values.agents.podAffinity }}
        podAntiAffinity:
          {{- if .Values.agents.podAffinity.hostname }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ include "h2ogpt.fullname" . }}
              topologyKey: kubernetes.io/hostname
          {{- end }}
          {{- if .Values.agents.podAffinity.zone }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ include "h2ogpt.fullname" . }}
                topologyKey: failure-domain.beta.kubernetes.io/zone
          {{- end }}
        {{- end }}
      {{- with .Values.agents.extraAffinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agents.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "h2ogpt.fullname" . }}-agents
          securityContext:
            {{- toYaml .Values.agents.securityContext | nindent 12 }}
          image: "{{ .Values.agents.image.repository }}:{{ .Values.agents.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agents.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
            - >
              python3 /workspace/generate.py
          ports:
            - name: agent
              containerPort: 5004
              protocol: TCP
          {{- if .Values.agents.livenessProbe }}
          livenessProbe:
            httpGet:
              path:  /
              scheme: HTTP
              port: http
            {{- toYaml .Values.agents.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.agents.readinessProbe }}
          readinessProbe:
            httpGet:
              path:  /
              scheme: HTTP
              port: http
            {{- toYaml .Values.agents.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.agents.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "h2ogpt.fullname" . }}-agents-config
          {{- if .Values.global.externalLLM.enabled }}
            - secretRef:
                name: {{ include "h2ogpt.fullname" . }}-external-llm-secret
          {{- end }}
          env:
          {{- range $key, $value := .Values.agents.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          {{- if .Values.global.externalLLM.enabled }}
            - name: H2OGPT_MODEL_LOCK
              value: {{ toJson .Values.global.externalLLM.modelLock | quote }}
            - name: H2OGPT_SCORE_MODEL
              value: None
          {{- end }}
          {{- if .Values.global.visionModels.enabled }}
            - name: H2OGPT_VISIBLE_VISION_MODELS
              value: {{ .Values.global.visionModels.visibleModels | quote }}
            - name: H2OGPT_ROTATE_ALIGN_RESIZE_IMAGE
              value: {{ .Values.global.visionModels.rotateAlignResizeImage | quote }}
          {{- end }}
          volumeMounts:
            - name: {{ include "h2ogpt.fullname" . }}-agents-volume
              mountPath: /workspace/.cache
              subPath: cache
            - name: {{ include "h2ogpt.fullname" . }}-agents-volume
              mountPath: /workspace/save
              subPath: save
            {{- if .Values.caCertificates }}
            - name: ca-certificates
              mountPath: /etc/ssl/certs/root-ca-bundle.crt
              subPath: root-ca-bundle.crt
            {{- end }}
            {{ with .Values.agents.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: {{ include "h2ogpt.fullname" . }}-agents-volume
          {{- if not .Values.agents.storage.useEphemeral }}
          persistentVolumeClaim:
            claimName:  {{ include "h2ogpt.fullname" . }}-agents-volume
          {{- else}}
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: {{ .Values.agents.storage.size | quote }}
                storageClassName: {{ .Values.agents.storage.class }}
          {{- end }}
        {{- if .Values.caCertificates }}
        - name: ca-certificates
          configMap:
            name: {{ include "h2ogpt.fullname" . }}-ca-certificates
        {{- end }}
        {{- with .Values.agents.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
