{{- if .Values.h2ogpt.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "h2ogpt.fullname" . }}-config
  namespace: {{ include "h2ogpt.namespace" . | quote }}
  labels:
    {{- include "h2ogpt.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.h2ogpt.overrideConfig }}
  {{ printf "H2OGPT_%s" $key | upper }}: {{ $value | quote }}
{{- end }}
{{- end }}
