{{- if and (.Values.tgi.enabled) (not .Values.h2ogpt.stack.enabled ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "h2ogpt.fullname" . }}-tgi-inference
  namespace: {{ include "h2ogpt.namespace" . | quote }}
spec:
  selector:
    app: {{ include "h2ogpt.fullname" . }}-tgi-inference
  ports:
    - protocol: TCP
      port: {{ .Values.tgi.service.port }}
      targetPort: 80
  type: {{ .Values.tgi.service.type }}
{{- end }}