{{- if and (.Values.tgi.enabled) (not .Values.tgi.storage.useEphemeral)}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "h2ogpt.fullname" . }}-tgi-inference-volume
  namespace: {{ include "h2ogpt.namespace" . | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.tgi.storage.class }}
  resources:
    requests:
      storage: {{ .Values.tgi.storage.size | quote }}
{{- end }}
