{{- if and ( and .Values.h2ogpt.enabled .Values.h2ogpt.agents.enabled) .Values.agents.enabled }}
  {{- fail " Both agents in both h2ogpt.agents cannot be enabled. Enably only one and try again" }}
{{- end }}
