{{- if and .Values.vllm.enabled .Values.tgi.enabled }}
  {{- fail "Both TGI and vLLM cannot be enabled at the same time. Enable only one and try again" }}
{{- end }}
{{- if and .Values.vllm.enabled .Values.lmdeploy.enabled }}
  {{- fail "Both lmdeploy and vLLM cannot be enabled at the same time. Enable only one and try again" }}
{{- end }}
{{- if and .Values.lmdeploy.enabled .Values.tgi.enabled }}
  {{- fail "Both TGI and lmdeploy cannot be enabled at the same time. Enable only one and try again" }}
{{- end }}
{{- if .Values.h2ogpt.stack.enabled }}
  {{- if not (and .Values.vllm.enabled .Values.h2ogpt.enabled) }}
    {{- fail "If h2oGPT stack is enabled, both vLLM and h2oGPT should be enabled" }}
  {{- end }}
{{- end }}